name: cui-test-mockwebserver-junit5

release:
  current-version: 1.5.0
  next-version: 1.6-SNAPSHOT
  create-github-release: true

maven-build:
  java-versions: '["21","25"]'
  java-version: '21'
  enable-snapshot-deploy: true
  maven-profiles-snapshot: 'release-snapshot,javadoc'
  maven-profiles-release: 'release,javadoc'
  npm-cache: false

sonar:
  project-key: cuioss_cui-test-mockwebserver-junit5
  enabled: true
  skip-on-dependabot: true

pages:
  reference: cui-test-mockwebserver-junit5
  deploy-at-release: true

github-automation:
  auto-merge-build-versions: true
  auto-merge-build-timeout: 300

consumers:
  - cuioss-parent-pom:version.cui.test.mockwebserver
  - nifi-extensions:version.cui.test.mockwebserver

dependency-propagation:
  group-id: de.cuioss.test
  artifact-id: cui-test-mockwebserver-junit5
  scope: dependency
