name: cui-test-mockwebserver-junit5
pages-reference: cui-test-mockwebserver-junit5
sonar-project-key: cuioss_cui-test-mockwebserver-junit5
release:
  current-version: 1.0.0
  next-version: 1.1.0-SNAPSHOT
