= cui-test-mockwebserver-junit5

== Status

image:https://github.com/cuioss/cui-test-mockwebserver-junit5/actions/workflows/maven.yml/badge.svg[Java CI with Maven,link=https://github.com/cuioss/cui-test-mockwebserver-junit5/actions/workflows/maven.yml]
image:http://img.shields.io/:license-apache-blue.svg[License,link=http://www.apache.org/licenses/LICENSE-2.0.html]
image:https://maven-badges.herokuapp.com/maven-central/de.cuioss/cui-test-mockwebserver-junit5/badge.svg[Maven Central,link=https://maven-badges.herokuapp.com/maven-central/de.cuioss/cui-test-mockwebserver-junit5]

https://sonarcloud.io/summary/new_code?id=cuioss_cui-test-mockwebserver-junit5[image:https://sonarcloud.io/api/project_badges/measure?project=cuioss_cui-test-mockwebserver-junit5&metric=alert_status[Quality
Gate Status]]
image:https://sonarcloud.io/api/project_badges/measure?project=cuioss_cui-test-mockwebserver-junit5&metric=ncloc[Lines of Code,link=https://sonarcloud.io/summary/new_code?id=cuioss_cui-test-mockwebserver-junit5]
image:https://sonarcloud.io/api/project_badges/measure?project=cuioss_cui-test-mockwebserver-junit5&metric=coverage[Coverage,link=https://sonarcloud.io/summary/new_code?id=cuioss_cui-test-mockwebserver-junit5]


https://cuioss.github.io/cui-test-mockwebserver-junit5/about.html[Generated Documentation on github-pages]

== What is it?

This is a template repository for creating java-modules for cui-open-source-projects. This incorporates all necessary java-structures, including `pom.xml`, sensible project-documentation, 
an predefined github pipelines. 

It is meant to be used as copy-paste-template.

=== Maven Coordinates

[source,xml]
----
    <dependency>
        <groupId>de.cuioss</groupId>
        <artifactId>cui-test-mockwebserver-junit5</artifactId>
    </dependency>
----

=== Further Steps

* `pom.xml`: Adjust `name` and `description` elements
* Adjust `module-info` accordingly
* `pom.xml`: Adjust property `maven.jar.plugin.automatic.module.name` according to your `module-info`
* `src/site/asciidoc/about.adoc`: Adjust content
* Review / Enable the elements under 'Security' Tab
* Review / Add Collaborators
* Add (link) the resulting maven-documentation: https://github.com/cuioss/cuioss.github.io/edit/main/README.md[github.io-documentation] 
