name: Update README
on:
  push:
    paths:
      - 'README.adoc'
      - 'docs/**/*.adoc'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Asciidoctor
        run: sudo apt-get install -y asciidoctor

      - name: Generate HTML
        run: asciidoctor README.adoc -o README.html

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.html
          git commit -m "Update README.html" || echo "No changes to commit"
          git push